### ISSUE TITLE
 Not in the npm registry.

### ISSUE THREAD

**Issue by ashikazeez** [magicwebes/ipay88-sdk#1]
**Terminal Error:** Registry returned 404 for GET on https://registry.npmjs.org/react-native-ipay88-sdk
'react-native-ipay88-sdk' is not in the npm registry.
You should bug the author to publish it (or use the name yourself!)

**Comment by myussufz** [comment]
I m still doing the repo. Maybe today or tomorrow, you start to use the repo

**Comment by myussufz** [comment]
I fixed the bugs. Please try to reinstall the package
